In [2]:
import numpy as np    # ! pip install numpy   import에서 하고 싶은 것들이 설치가 안 되어있을 때 설치해주는 코드

In [10]:
a1 = np.array([1, 2, 3, 4, 5])    # 다른 코드를 읽어들어왔을 때
print([1, 2, 3, 4, 5])    # 배열이랑 다르다는 것을 보여줌
print(a1)
print(type(a1))           # ndarray는 데이터 타입이 동일해야 한다.

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [22]:
a2 = np.arange(10)
print(a2)

# 변수 a3, 100 아래 3의 배수

a3 = np.arange(3, 100, 3)
print(a3)

# 1에서부터 10 아래 0.5씩 증가하는 숫자, step = 0.5
a4 = np.arange(1.3, 10, 0.5)
print(a4)

# lista = [i for i in range(1.3, 10, 0.5)]   파이썬은 실수 x

[0 1 2 3 4 5 6 7 8 9]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
[1.3 1.8 2.3 2.8 3.3 3.8 4.3 4.8 5.3 5.8 6.3 6.8 7.3 7.8 8.3 8.8 9.3 9.8]


In [39]:
a4 = np.linspace(0, 10, 10)       # 0에서부터 10까지 "10등분", 그래프를 그릴 때, x 값을 넣을 때
print(a4)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [53]:
a5 = np.zeros(5)      # 0으로 채워짐, 박스 개수 설정할 때 사용, 그냥 숫자여도 .이 찍혀있다면 실수형이다,
print(a5)

a6 = np.ones(5, dtype = np.int64)       # 1로 채워짐
print(a6)
a6.astype(np.float64)

[0. 0. 0. 0. 0.]
[1 1 1 1 1]


array([1., 1., 1., 1., 1.])

In [54]:
lista = [1, 2, 3.5, 4.2]
a7 = np.array(lista)
print(a7)

listb = [1, 2, 'abc', 'def']
a8 = np.array(listb)
print(a8)
#a8.astype(np.int64)

[1.  2.  3.5 4.2]
['1' '2' 'abc' 'def']


In [68]:
print(a7.dtype)    # astype = 메소드임
print(a7.ndim)     # 몇 차원인지 알려줌
print(a7.shape)    # 1차원의 length가 4, 2차원은 x, tuple로 돌려줌.
print(a7.size)     # shape랑 비슷하지만 size는 배열 안의 모든 갯수를 의미한다.

print(a7. itemsize)   # 데이터 타입의 byte 사이즈를 의미한다.
print(a7.data)

float64
1
(4,)
4
8


In [77]:
a10 = np.arange(10, 100, 5)
print(a10)
# 특정 인덱스
print(a10[0])

# 스타트, 스탑
print(a10[:-1])

# 스탙, 스탑, 스텝
print(a10[:-1:3])


[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
10
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90]
[10 25 40 55 70 85]
18


In [83]:
a10 = np.arange(10, 100, 5)
print(a10)
print(a10[[1, 3, 7]])      # 인덱스의 1번, 3번, 7번을 출력

list10 = [x for x in range(10, 100, 5)]
print(list10)
# print(list10[[1, 3, 7]])

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[15 25 45]
[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]


In [88]:
a10 = np.arange(10, 100, 5)
print(a10)
print(a10[a10 % 10 == 5])

# bool list 내가 원하는 것만 뽑아오기
x = (a10 % 10 == 5)
print(x)
print(x.shape)
print(a10.shape)
print(a10[x])

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[15 25 35 45 55 65 75 85 95]
[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True]
(18,)
(18,)
[15 25 35 45 55 65 75 85 95]


In [98]:
lista = [x for x in range(5)]
listb = [x for x in range(10, 15)]
print(lista)
print(listb)
print(lista + listb)         # 담는 것을 위주로 하기 때문에 list끼리 합체
print(lista - listb)         # list에 -는 아몰랑

[0, 1, 2, 3, 4]
[10, 11, 12, 13, 14]
[0, 1, 2, 3, 4, 10, 11, 12, 13, 14]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [3]:
a1 = np.arange(5)
a2 = np.arange(10, 15)
print(a1)
print(a2)
print('add:', a1 + a2)       # 계산 위주이기 때문에 같은 index끼리 덧셈을 함, 사칙연산이 되려면 배열 안의 갯수가 서로 맞아야 가능하다
print(np.concatenate((a1,a2)))      # list처럼 묶으려면 np.concatenate 안에 tuple로 묶어줘야 함.
print('sub:', a1 - a2)
print('mul:', a1 * a2)
print('div:', a1 / a2)

[0 1 2 3 4]
[10 11 12 13 14]
add: [10 12 14 16 18]
[ 0  1  2  3  4 10 11 12 13 14]
sub: [-10 -10 -10 -10 -10]
mul: [ 0 11 24 39 56]
div: [0.         0.09090909 0.16666667 0.23076923 0.28571429]
