In [41]:
import requests
import numpy as np

x= requests.get('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

In [42]:
raw_data = []
for line in x.text.split('\n'):
    raw_data.append(line.split(','))
    
for sample in raw_data:
    for i, value in enumerate(sample[:4]):
        if len(sample) < 1:         # 맨 마지막 부분에 빈 줄이 있는 것이 있으면 계속 진행
            continue
        try:
            sample[i] = float(value)
        except:
            sample[i] = 0.0
            
print(raw_data[:3])

[[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'], [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'], [4.7, 3.2, 1.3, 0.2, 'Iris-setosa']]


In [43]:
for sample in raw_data:
    if len(sample) < 2:
        continue
    if 'setosa' in sample[-1]:
        sample[-1] = 0.0
    elif 'versicolor' in sample[-1]:
        sample[-1] = 1.0
    elif 'virginica' in sample[-1]:
        sample[-1] = 2.0


# for e in raw_data:
#     if e[:-1] == 'Iris-setosa':
#         e[:-1] = 0
# print(raw_data)

In [52]:
np_data = np.array(raw_data)
np_data.shape
np_data

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ]])

### 기본 통계값
* 전체(150 샘플) 평균, 표준편차 - sepal length, sepal width, petal length, petal width)
* 품종별(50개씩) 평균, 표준편차
* Min Max Mean SD
* sepal length:
* 평균 np.mean()
* 표준편차 np.std()

In [99]:
# filter1 = np_data[:, -1] == 0

print(np.mean(np_data, axis = 0))
print(np.std(np_data, axis = 0))
# print(np.corrcoef(np_data.T))            # 상관도

[[ 1.         -0.10936925  0.87175416  0.81795363  0.78256123]
 [-0.10936925  1.         -0.4205161  -0.35654409 -0.4194462 ]
 [ 0.87175416 -0.4205161   1.          0.9627571   0.94904254]
 [ 0.81795363 -0.35654409  0.9627571   1.          0.95646382]
 [ 0.78256123 -0.4194462   0.94904254  0.95646382  1.        ]]


In [107]:
filter_setosa = np_data[:, -1] == 0.0
filter_versicolor = np_data[:, -1] == 1.0
filter_virginica = np_data[:, -1] == 2.0

print(np.mean(np_data[filter_setosa], axis = 0))
print(np.std(np_data[filter_setosa], axis = 0))

print(np.mean(np_data[filter_versicolor], axis = 0))
print(np.std(np_data[filter_versicolor], axis = 0))

print(np.mean(np_data[filter_virginica], axis = 0))
print(np.std(np_data[filter_virginica], axis = 0))

[5.006 3.418 1.464 0.244 0.   ]
[0.34894699 0.37719491 0.17176728 0.10613199 0.        ]
[5.936 2.77  4.26  1.326 1.   ]
[0.51098337 0.31064449 0.46518813 0.19576517 0.        ]
[6.588 2.974 5.552 2.026 2.   ]
[0.62948868 0.31925538 0.54634787 0.27188968 0.        ]
