In [2]:
import numpy as np

a1 = np.array([[1, 2, 3,], [10, 20, 30]])         # numpy 안에 있는 array 클래스 이름이 ndArray. ex) a1 : ndArray
print(a1)
print(a1.ndim)
print(a1.shape)
print(a1.size)

[[ 1  2  3]
 [10 20 30]]
2
(2, 3)
6


In [36]:
a2 = np.arange(20).reshape(4, 5)         # shape은 개수가 맞아야 실행이 된다. 아니면 오류가 뜸
print(a2)
print(a2.shape)          # (배열의 개수, 원소의 개수)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


In [37]:
a3 = a2.flatten()       # 몇 차원이었든 1차원으로 만들어줌,    원본을 그대로 복사해서 가져옴. ex) 사진을 편집해서 쓰는데 원본도 그대로 둠
a3[3] = 100
print(a3)
print(a2)

a4 = a2.ravel()        # 원본을 참조값으로 가져옴. ex) 사진을 편집하고 원본을 버리고 편집한 것을 저장
a4[3] = 200
print(a4)
print(a2)

[  0   1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[  0   1   2 200   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[  0   1   2 200   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


In [5]:
a2 = np.arange(20).reshape(4, 5)
print(a2)
# print(a2[1])
# print(a2[1, 2])
# print(a2[:, 1])       모두 선택, 1번 인덱스의 칼럼
# print(a2[:, 1:4])
# print(a2[:, 1:4:2])
# print(a2[1, :])
# print(a2[1:3, :])
# print(a2[::2, :)
print(a2[::2, 1:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]
[[ 1  2  3]
 [11 12 13]]


In [43]:
print(a2)
# print(a2.shape)      # axis(축)  0 = y축, 1 = x축, 2 = z축    shape을 봤을 때 가장 먼저 나오는 것이 y축이기 때문에 y축이 0이다
# print(a2.sum())
# print(a2.sum(axis=0))
print(a2.sum(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[10 35 60 85]


In [44]:
print(a2, a2.shape)
a3 = a2.T         # x축 y축 변환, Transform의 T
print(a3, a3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (4, 5)
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]] (5, 4)


In [46]:
print(a2, a2.shape)
np.moveaxis(a2, [0], [1])     # axis를 지정해서 변환
print(a3, a3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (4, 5)
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]] (5, 4)


In [64]:
a10 = np.arange(5, 20).reshape(3,5)
print(a10, a10.shape)
print(a10[:, 2:4])

a11 = a10[:, 2:4]
print(a11.sum(axis = 0))
print(a11)
print(np.mean(a11, axis = 0))

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (3, 5)
[[ 7  8]
 [12 13]
 [17 18]]
[36 39]
[[ 7  8]
 [12 13]
 [17 18]]
[12. 13.]


In [ ]:
# ptp(a[, axis, out, keepdims])          max - min
# quantile(a, q[, axis, out, overwrite_input, ...])   4분위수
# average(a[, axis, weights, returned, keepdims])    평균
# mean(a[, axis, dtype, out, keepdims, where])       평균

In [7]:
a1 = np.arange(0, 10).reshape(2,5)
a2 = np.arange(100, 110).reshape(2,5)
print(a1)
print(a2)

a3 = np.concatenate((a1,a2), axis = 1)       # ndArray를 붙임. 배열을 붙이는 것과 동일. 단 tuple로 만들어줘야 함
# print(a3)
a4 = np.hstack((a1, a2))           # 수평. axis = 1과 동일
# print(a4)
a5 = np.vstack((a1, a2))           # 수직. axis = 0과 동일
print(a5)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[100 101 102 103 104]
 [105 106 107 108 109]]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [100 101 102 103 104]
 [105 106 107 108 109]]


In [85]:
print(a4)
a6 = np.hsplit(a4, 5)         # np.hsplit(변수, 몇 등분할지) -> 수평으로 출력
print(a6)
a7 = np.vsplit(a4, 2)         # np.vsplit(변수, 몇 등분할지) -> 수직으로 출력
print(a7)

[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]
[array([[0, 1],
       [5, 6]]), array([[2, 3],
       [7, 8]]), array([[  4, 100],
       [  9, 105]]), array([[101, 102],
       [106, 107]]), array([[103, 104],
       [108, 109]])]
[array([[  0,   1,   2,   3,   4, 100, 101, 102, 103, 104]]), array([[  5,   6,   7,   8,   9, 105, 106, 107, 108, 109]])]


In [88]:
a7 = a4.T
# print(a7)
np.vsplit(a7, 5)

[array([[0, 5],
        [1, 6]]),
 array([[2, 7],
        [3, 8]]),
 array([[  4,   9],
        [100, 105]]),
 array([[101, 106],
        [102, 107]]),
 array([[103, 108],
        [104, 109]])]

In [94]:
a2 = np.arange(20).reshape(4, 5)
print(a2)
filter1 = a2[:, 0] % 10 == 5
print(a2[filter1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]
