### kosis 부산광역시 가스 사용량 2010 - 2020

- 년도별 도시가스 / 프로판 판배량 비율
    프로판 가스보다 도시가스 사용량이 점점 늘어나는가
    도시가스 : 14.05206635 11.90604976 10.781497    8.04722945  6.26402748  5.49942633
  5.50188799  5.02306741  5.12714633  6.19599723  8.58577885 13.01582583
  
    프로판 : 11.2772806   9.78934166  9.77062173  7.93725079  7.61398714  6.33512027
  6.83228223  6.78390598  7.17860095  7.40166371  8.52633747 10.55360748

- 년도별 도시가스, 년도별 프로판 사용량 상관도
    도시가스 사용량이 점점 많아지고 있는가
    프로판 가스 사용량은 점점 줄어들고 있는가
    
- 도시가스
    년도별 겨울(10, 11, 12, 1, 2, 3) 평균사용량/
           비겨울(4, 5, 6, 7, 8, 9) 평균사용량
           --> ttest (평균 사용량에 차이가 있는가)
    같은 분석을, 프로판 / 부탄 가스를 대상으로도 실행.
      

In [1]:
import numpy as np
import matplotlib.pyplot as plt

def my_split(s):
    block_start = False
    start_index = 0
    ret_list=[]
    for i, c in enumerate(s):
        if block_start==False:
            if c==',':
                ret_list.append(s[start_index:i])
                start_index=i+1
            elif c=='"':
                block_start=True
                start_index = i
        else:
            if c=='"':
                block_start=False
    if s[-1]!=',':
        ret_list.append(s[start_index:])
    return ret_list

def split_len(data_list):
    len_list=[]
    for e in data_list:
        len_list.append(len(e))
    print(set(len_list))
    if len(set(len_list))>1:
        for i in set(len_list):
            print(i, len_list.count(i))
    return set(len_list)

def dist_np(p1, p2): #  [3,10]  [5,25]
    return math.sqrt(sum((p2-p1)**2))

In [4]:
csv_data = []
with open('가스공급량_20230217170922.csv') as f:
    for line in f:
        csv_data.append(my_split(line[:-1]))
        
# print(csv_data[:3])
for i in enumerate(csv_data[:2]):
    print(i)

(0, ['"시점"', '"월별(1)"', '도시가스 (천㎥)', '도시가스 (천㎥)', '프로판 (ton)', '프로판 (ton)', '부탄 (ton)', '부탄 (ton)'])
(1, ['"시점"', '"월별(1)"', '판매소수 (개)', '판매량', '판매소수 (개)', '판매량', '판매소수 (개)', '판매량'])


In [57]:
# 연도별 도시가스 / 프로판 판매량 비율

np_data = np.array(csv_data[2:])
# year_np = np_data[:, 0].reshape(11, 12).astype(np.str)

gas_cnt = np_data[:, 3].reshape(11, 12).astype(np.int64)
pro_cnt = np_data[:, 5].reshape(11, 12).astype(np.int64)

gas_mean = sum(gas_cnt) * 100 / np.sum(gas_cnt)
pro_mean = sum(pro_cnt) * 100 / np.sum(pro_cnt)

gas_data = np.concatenate((gas_mean, pro_mean))

print(gas_data)

[14.05206635 11.90604976 10.781497    8.04722945  6.26402748  5.49942633
  5.50188799  5.02306741  5.12714633  6.19599723  8.58577885 13.01582583
 11.2772806   9.78934166  9.77062173  7.93725079  7.61398714  6.33512027
  6.83228223  6.78390598  7.17860095  7.40166371  8.52633747 10.55360748]


In [73]:
#년도별 겨울(10, 11, 12, 1, 2, 3) 평균사용량 / 비겨울(4, 5, 6, 7, 8, 9) 평균사용량

np_cnt = np_data[:, 3].reshape(22, 6).astype(np.int64)


print(np_cnt[:, :])

[[179086 139496 143581 114671  79649  70646]
 [ 68554  65293  62398  77985 113800 160555]
 [200683 144076 145930 103965  83355  74141]
 [ 70168  64615  66426  81153  99188 164254]
 [178441 173008 144653 103329  83927  74280]
 [ 75623  68263  71611  83074 122244 181273]
 [191681 152480 129637 114523  88225  72520]
 [ 73740  64914  63962  81581 117201 167572]
 [175047 150507 143724 101976  84307  71273]
 [ 74293  67698  70148  84946 109302 179852]
 [177213 150835 147748 107320  79993  74101]
 [ 76227  65733  69305  84487 108315 155704]
 [192790 172558 148808 103696  85581  75733]
 [ 73754  66741  70137  82216 122259 166731]
 [188340 176003 156492 108379  82001  79125]
 [ 76376  72262  75554  82870 125300 204669]
 [215573 186204 157745 108188  93931  77279]
 [ 77269  71037  72533  94793 125270 182018]
 [210982 167223 144388 121169  90821  79148]
 [ 78992  73847  73547  87861 117687 182975]
 [190840 167473 149045 115783  84634  73876]
 [ 77494  70507  70848  85288 122942 200163]]


In [ ]:
# t = set()
# for e in csv_data:
#     t.add(len(e))
# print(t)
# np_data = np.array(csv_data[2:])
# np_data = np_data[:, 2:].astype(np.int64)