In [4]:
# python list

lista = []
print(lista)

lista.append('a')
print(lista)

[]
['a']


In [15]:
# numpy ndarray
import numpy as np

array1 = np.array(lista)
array2 = np.array([1, 2, 3, 4])
array3 = np.array([x for x in range(5)])

print(array1)
print(array2)
print(array3)
print(array3[[1, 4]])
print(array3[array3 % 2 == 0])
print(array3[array3 > 2])

['a']
[1 2 3 4]
[0 1 2 3 4]
[1 4]
[0 2 4]
[3 4]


In [19]:
# for, if

# for i in array3:
#     print(i)
    
for i in range(5):        # np.arange(5)
    if i > 2:
        print(i)

3
4


In [38]:
# function

def function_name(n):
#     print(n * 10)
    return n * 10

return_value = function_name(20)
print('return_value:', return_value)

assert function_name(100) == 1000

return_value: 200


In [134]:
# random
import random

random.seed()     # 시드 값 맞추기

listb = []

for i in range(10):
    listb.append(random.randint(0, 100)) # 0에서부터 100까지 랜덤 숫자
print(listb)

listc = [random.randint(0, 100) for _ in range(10)]
print(listc)

# listb에서 50보다 큰 것.

np_b = np.array(listb)

print(np_b[np_b > 50])
print(len(np_b[np_b > 50]))

[25, 8, 56, 67, 86, 73, 15, 87, 81, 11]
[98, 66, 87, 33, 1, 29, 97, 61, 98, 34]
[56 67 86 73 87 81]
6
